services:
  app:
    image: eesteclcskopje/lcskopje_private:eestecmk
    environment:
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "6969:3000"
  database:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD={MARIADB_ROOT_PASSWORD}