version: "3"
services:
  frontend:
    container_name: eestecmk-nextjs
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "6969:3000"
  
  backend:
    container_name: eestecmk-strapi
    environment:
      - HOST=0.0.0.0
      - PORT=1337
      - APP_KEYS=1/Zd+Set34q2UOja4vEkDg==,mDNQFDqJiGJBNWDBx1GfPA==,U98PhuxIvLQ4zqslwK2IKg==,EukGMbtWczC9Qr5tEjazkg==
      - API_TOKEN_SALT=6FasummRDPv+ALLfbPFtaA==
      - ADMIN_JWT_SECRET=Uk783OqunAoy9rs56qSCLg==
      - TRANSFER_TOKEN_SALT=iVmekpJUWp7Rr75jvkEs5A==
      # Database
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_NAME=eestecmk
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=postgres
      - DATABASE_SSL=false
      - JWT_SECRET=VoykdCOSRXI9tUNFFR6plA==

    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "42069:1337"
    depends_on:
      - database

  database:
    image: postgres
    environment:
      - POSTGRES_DB=eestecmk
      - POSTGRES_USER=strapi
      - POSTGRES_PASSWORD=postgres
    volumes:
      - eestec_db:/var/lib/postgresql/data

volumes:
  eestec_db: