services:
  app:
    image: eesteclcskopje/lcskopje_private:eestecmk
    ports:
      - "6969:3000"
  database:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}