name: Deploy to Production

on:
  push:
    branches:
      - production

jobs:
  build-and-push-docker-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push backend Strapi Image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/lcskopje_private:eestecmk-api

      - name: Build and push frontend NextJS Image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/lcskopje_private:eestecmk

      - name: Login to Base Server and Restart Services
        env:
          BASE_SERVER_PB_KEY: ${{ secrets.BASE_SERVER_PB_KEY }}
        run: |
          echo ${{secrets.BASE_SERVER_PB_KEY}} > temp_secret
          ssh -p 1122 -i temp_secret -tt eestec@ip.42.mk
          cd eestecmk
          docker-compose pull
          docker-compose up
